site_name: 咩咩的笔记

nav:
  - 主页: 'index.md'
  - 笔记:
    - 离散数学:
      - 命题逻辑: '离散数学/2-命题逻辑.md'
      - 一阶逻辑: '离散数学/3-一阶逻辑.md'
      - 证明方法: '离散数学/4-证明方法.md'
      - 集合: '离散数学/5-集合.md'
      - 关系: '离散数学/6-关系.md'

theme:
  name: readthedocs
  local: zh_CN

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
#  - markdown_katex:
#      no_inline_svg: True
#      insert_fonts_css: True

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js