site_name: 咩咩的笔记

nav:
  - 主页: 'index.md'
  - 笔记:
    - 数字电路:
      - 介绍: '数字电路/1. 介绍.md'
      - 数字系统、运算和编码: '数字电路/2. 数字系统、运算和编码.md'
      - 逻辑门: '数字电路/3. 逻辑门.md'
      - 布尔代数: '数字电路/4. 布尔代数.md'
      - 组合逻辑分析: '数字电路/5. 组合逻辑分析.md'
      - 组合逻辑功能模块: '数字电路/6. 组合逻辑功能模块.md'
      - 锁存器、触发器和定时器: '数字电路/7. 锁存器、触发器和定时器.md'
      - 移位寄存器: '数字电路/8. 移位寄存器.md'
      - 计数器: '数字电路/9. 计数器.md'
      - 储存器: '数字电路/10. 储存器.md'
      - 模数转换: '数字电路/11. 模数转换.md'
    - 离散数学:
      - 命题逻辑: '离散数学/2-命题逻辑.md'
      - 一阶逻辑: '离散数学/3-一阶逻辑.md'
      - 证明方法: '离散数学/4-证明方法.md'
      - 集合: '离散数学/5-集合.md'
      - 关系: '离散数学/6-关系.md'
      - 函数: '离散数学/7-函数.md'
      - 计数与组合: '离散数学/8-计数与组合.md'
      - 图与树: '离散数学/9-图与树.md'
    - 计算机组成原理:
      - 计算机概览: '计算机组成原理/1. 计算机概览.md'
      - 指令: '计算机组成原理/2. 指令.md'
      - 计算机中的运算: '计算机组成原理/3. 计算机中的运算.md'
      - 'MIPS CPU设计': '计算机组成原理/4. MIPS CPU设计.md'
      - 存储器层次结构: '计算机组成原理/5. 存储器层次结构.md'
      - 计算机系统总线: '计算机组成原理/6. 计算机系统总线.md'
      - 输入输出系统: '计算机组成原理/7. 输入输出系统.md'
    - 计算机组成原理实验:
      - 加法器: '计算机组成原理实验/1/1.md'
      - 有限状态机: '计算机组成原理实验/2/2.md'
      - MIPS指令集1: '计算机组成原理实验/3/3.md'
      - MIPS指令集2: '计算机组成原理实验/4/4.md'
      - 存储器实验: '计算机组成原理实验/5/5.md'
      - '寄存器堆与 ALU 设计实验': '计算机组成原理实验/6/6.md'
      - 存储器与控制器实验: '计算机组成原理实验/7/7.md'
      - 单周期处理器实验: '计算机组成原理实验/8/8.md'
      - 多周期处理器实验: '计算机组成原理实验/9/9.md'
      - 多周期处理器综合性开放实验: '计算机组成原理实验/10/10.md'
    - 概率论:
      - 概率论的基本概念: '概率论/1. 概率论的基本概念.md'
      - 随机变量及其分布: '概率论/2. 随机变量及其分布.md'
      - 多维随机变量及其分布: '概率论/3. 多维随机变量及其分布.md'
      - 随机变量的数字特征: '概率论/4. 随机变量的数字特征.md'
      - 大数定律及中心极限定理: '概率论/5. 大数定律及中心极限定理.md'
      - 样本及抽样分布: '概率论/6. 样本及抽样分布.md'
      - 参数估计: '概率论/7. 参数估计.md'
      - 假设验证: '概率论/8. 假设验证.md'
    - 信号与系统:
      - 信号与系统: '信号与系统/1. 信号与系统.md'
      - 线性时不变系统: '信号与系统/2. 线性时不变系统.md'
      - 周期信号的傅里叶级数表示: '信号与系统/3. 周期信号的傅里叶级数表示.md'
      - 连续时间傅里叶变换: '信号与系统/4. 连续时间傅里叶变换.md'
      - 离散时间傅里叶变换: '信号与系统/5. 离散时间傅里叶变换.md'

theme:
  name: readthedocs
  local: zh_CN

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
#  - markdown_katex:
#      no_inline_svg: True
#      insert_fonts_css: True

plugins:
  - search: 
      indexing: 'titles'

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://fastly.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js